### ISSUE TITLE
Add Apple sponsorship logo to Sponsors page

### ISSUE THREAD

**Issue by DavidFlatla** [ASSETS-Conference/assets2024#119]
Apple contributed at 'Gold' level ($10k).
Logo design and layout details in email forwarded by Faustina.
Set this up on the 'testing' server so we can send a link and/or screenshot to Apple for approval prior to making it live.
Thanks!

**Comment by surajgoraya** [comment]
Resolved in #147 

Pushed to prod 06/24/24 - 12:45:00
