### ISSUE TITLE
change to the Workshops page

### ISSUE THREAD

**Issue by f-hwang** [ASSETS-Conference/assets2024#144]
Original text: A workshop proposal must be prepared according to the ACM Master Article Submission Templates (single column). It must be submitted via the PCS Submission System as a single PDF file.

Change requested: A workshop proposal must be prepared according to the ACM Master Article Submission Templates (single column). The submission **should not** be anonymized and must be submitted via the PCS Submission System as a single PDF file.

**Comment by surajgoraya** [comment]
Fixed and deployed to Prod in #145
