### ISSUE TITLE
Add Alert (like Workshop CfP alert about format update) that PCS is open

### ISSUE THREAD

**Issue by DavidFlatla** [ASSETS-Conference/assets2024#146]
Add an alert to *somewhere* (will discuss in meeting today) that PCS is now open for Posters & Demos, Workshops, Doctoral Consortium (DC), Student Research Competition (SRC), and Experience Reports (ERs).
I think this alert could visually follow the 'alert' on the Workshop Call-for-Papers (CfP) page (an update on Workshop format).
Possible locations are the individual CfPs for the tracks listed above.
Another possible location is on the main conference page itself above the important dates.
David

**Comment by surajgoraya** [comment]
Completed in #148
