### ISSUE TITLE
PENDING: remote attendance details are coming and need to go live very quickly 

### ISSUE THREAD

**Issue by DavidFlatla** [ASSETS-Conference/assets2024#177]

**Comment by DavidFlatla** [comment]
Please add the information to 'Attending Overview' that is in this doc:
https://docs.google.com/document/d/18rIZx2NwbEaIHf5tScPDwtaMXm8otgE_4HOW_7OPDGk/edit
between 'Virtual Attendance' [inclusive] and 'TABLE FOR ALL CHAIRS TO CHECK' [exclusive].

**Comment by surajgoraya** [comment]
resolved in #196 

https://assets24.sigaccess.org/attending/overview/#virtual-attendance
